### PR TITLE
Support multiple calendars

### PR DESCRIPTION
**Pull request by twomice**
Addresses the request for multiple calendars on a single site, as described in https://github.com/osseed/com.osseed.eventcalendar/issues/48

### CODE REVIEW

**Comment by pranav45** [comment]
@twomice Thanks for sharing this.

We have reviewed the PR it works fine !

Now it's showing the multiple calendars according to settings. Have we think about what we can do with default calendar which is at Events->Show Events Calendar(civicrm/showevents) ? Can we show all events on that or simply we can add filter for calendars or are you removing that all toghther?

Any thoughts on this ? so we can merge this PR and relase the new version of extensions?

**Comment by pranav45** [comment]
@twomice Thanks again. We will think on this how we can upgrade once this is fixed we can merge this PR, as upgrade is important.

**Comment by pranav45** [comment]
@twomice Thanks for the PR. We have covered this functionality under the new release with code cleanup.

**Comment by twomice** [comment]
Super, thanks @pranav45

**Pull request closed without merging**
